AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Escola de software - Usuarios - Lambda Criar usuarios FN
Parameters:
  Environment:
    Description: Environment
    Type: String
  TableName:
    Description: Table Name
    Type: String
  NomeFilaSqs:
    Description: Nome da fila SQS
    Type: String

Resources:  
  UsuariosLambdaCriarUsuarioFn:
    Type: AWS::Serverless::Function
    Properties:
      Description: register an user on database
      FunctionName: !Join ["_", [!Ref Environment, "escoladesoftware-usuarios-lambdacriarusuariofn"]]
      Handler: app.lambdaHandler
      CodeUri: src/built
      Runtime: nodejs18.x
      Timeout: 3
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonSQSFullAccess
      Environment:
        Variables:
          TableName: !Ref TableName
          NomeFilaSqs: !Ref NomeFilaSqs
    Tags: 
      - Key: Ambiente
        Value: !Ref Environment
      - Key: Microservico
        Value: Usuarios
      - Key: Servico
        Value: Lambda

  UsuariosLambdaCriarUsuarioLogGroup: 
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: !Join ["", ["/aws/lambda/", !Ref Environment, "_escoladesoftware-usuarios-lambdacriarusuariofn"]]
      RetentionInDays: 3
      Tags: 
        - Key: Ambiente
          Value: !Ref Environment
        - Key: Microservico
          Value: Usuarios
        - Key: Servico
          Value: LogGroup
